environment: 'dev'

redis:
  host: 'redis' # use 127.0.0.1 if running outside of docker
  port: '6379'
  password: ''
  DB: 0
  expiry: 60

ccache:
  capacity: 10
  expiry: 60

proxy:
  host: '0.0.0.0'
  port: '8082'
