version: "2"

services:
  assignment:
    image: golang:1.9.2-alpine
    volumes:
      - .:/go/src/github.com/bluehawk27/assignment
    working_dir: /go/src/github.com/bluehawk27/assignment
    ports:
     - "8082:8082"
    command: go run main.go
    links:
      - redis

  redis:
    image: redis:alpine
