version: "2"

services:
  assignment:
    image: golang:1.9.2-alpine
    entrypoint: ["go", "run", "src/github.com/bluehawk27/assignment/main.go"]
    volumes:
      - .:/go/src/github.com/bluehawk27/assignment
    working_dir: /go/src/github.com/bluehawk27/assignment
    ports:
     - "8082:8082"
    links:
      - redis

  redis:
    image: redis:alpine
    volumes:
    - ./local-redis.conf:/usr/local/etc/redis/redis.conf
